import Head from "next/head";
import Header from "../components/Header";
import { useEffect, useState, useContext } from "react";
import { useRouter } from "next/router";
import Left from "../components/Home/Left/Left";
import Feed from "../components/Home/Feed/Feed";
import Right from "../components/Home/Right/Right";

import { dataContext } from "../Helper/DataProvider";

export default function Home() {
  const travlerData: any = useContext(dataContext);
  const { dataSetter, data } = travlerData;

  const [userName, setUserName] = useState<string>("");
  const router = useRouter();

  useEffect(() => {
    async function getUser() {
      const emailAndToken = localStorage.getItem("tapp_eAt") as string;
      if (emailAndToken) {
        const response = await fetch("/api/home", {
          method: "POST",
          headers: {
            "Content-Type": "application/json;charset=utf-8",
          },
          body: emailAndToken,
        });

        const traveler: any = await response.json();
        dataSetter(traveler);
        setUserName(traveler?.name);
      }
    }

    getUser();

    console.log("useEffect");
  }, [router, dataSetter]);

  return (
    <div>
      <Head>
        <title>TravelBook - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex">
        <Left userName={userName} />
        <Feed />
        <Right />
      </main>
    </div>
  );
}
