import Head from "next/head";
import Header from "../components/Header/Header";
import ProfileHead from "../components/Profile/ProfileHead";
import Divider from "../components/Divider";
import ProfileBody from "../components/Profile/ProfileBody";

const User = () => {
  return (
    <div className="w-full">
      <Head>
        <title>TravelBook - Mskhan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="w-full">
        <ProfileHead />
        <Divider customClass="mt-[14rem]" />
        <ProfileBody />
      </main>
    </div>
  );
};

export default User;
