import { useContext, useState, useEffect } from "react";
import Head from "next/head";
import Header from "../../components/Header/Header";
import Left from "../../components/Home/Left/Left";
import SearchResults from "../../components/Search/SearchResults";

import dataContext from "../../Helper/dataContext";

import { useRouter } from "next/router";
export default function Search() {
  const [userName, setUserName] = useState<string>("not set");
  const [searchResults, setSearchResults] = useState<Array<Object>>([]);

  const traveller: any = useContext(dataContext);
  const { data } = traveller;

  const router = useRouter();

  const person = router.query.person;

  useEffect(() => {
    setUserName(data.name);

    async function fetchTravellers() {
      const response = await fetch("/api/search/", {
        method: "POST",
        headers: {
          "Content-Type": "application/json;charset=utf-8",
        },
        body: JSON.stringify({ query: person }),
      });
      const jsonResponse = await response.json();
      setSearchResults(jsonResponse);
    }
    fetchTravellers();
  }, [data.name, person]);

  return (
    <div>
      <Head>
        <title>TravelBook - Travellers</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <main className="flex">
        <Left />
        <SearchResults results={searchResults} />
      </main>
    </div>
  );
}
