import Head from "next/head";
import { useState, useEffect, useContext } from "react";
import Header from "./../../components/Header";
import Left from "../../components/Home/Left/Left";
import dataContext from "../../Helper/dataContext";

export default function Friends() {
  const travellerData: any = useContext(dataContext);
  const { data } = travellerData;
  const [friends, setFriends] = useState();

  useEffect(() => {
    console.log(data);
    async function fetchFriends() {
      const response = await fetch("/api/friends", {
        method: "POST",
        headers: {
          "Content-Type": "application/json;charset=utf-8",
        },
        body: JSON.stringify(data?.followers),
      });
    }

    fetchFriends();
    console.log("friends useEffect");
  }, [travellerData]);
  return data ? (
    <div>
      <Head>
        <title>TravelBook</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <main>
        <Left userName={data?.name} />
      </main>
    </div>
  ) : null;
}
